export const REALISATIONS = [
  {
    src: "/images/realisations/ossature-metallique-faux-plafond-en-cours.jpg",
    alt: "Ossature métallique de faux plafond en cours d'installation sous une charpente en bois, avec des câbles visibles.",
    caption: "La structure métallique du futur faux plafond est installée sous la charpente, tandis que des câbles et des plaques sont présents sur le chantier.",
    category: "plafond",
  },
  {
    src: "/images/realisations/cloison-plaques-platre-ossature-en-cours.jpg",
    alt: "Cloisons en plaques de plâtre avec ossature métallique et câbles visibles dans une pièce en chantier.",
    caption: "Ossature métallique et plaques de plâtre partiellement posées, avec câbles apparents.",
    category: "cloison",
  },
  {
    src: "/images/realisations/pose-isolation-doublage-murs.jpg",
    alt: "Murs en cours de doublage avec isolant visible entre les montants métalliques et plaques de plâtre déjà posées autour des fenêtres.",
    caption: "Isolation visible entre les montants métalliques, avec doublage en plaques de plâtre partiellement réalisé dans la pièce.",
    category: "doublage",
  },
  {
    src: "/images/realisations/ossature-metallique-plafond-en-cours.jpg",
    alt: "Ossature métallique de faux plafond en cours de pose dans une pièce en rénovation.",
    caption: "Ossature métallique du plafond en cours d'installation dans une pièce en chantier.",
    category: "plafond",
  },
  {
    src: "/images/realisations/faux-plafond-plaques-platre-en-cours.jpg",
    alt: "Pièce en chantier avec un faux plafond en plaques de plâtre partiellement posé et une ouverture visible dans la structure.",
    caption: "Faux plafond en plaques de plâtre en cours d'installation dans une pièce aux murs en blocs apparents.",
    category: "plafond",
  },
  {
    src: "/images/realisations/ossature-metallique-cloison-isolation.jpg",
    alt: "Ossature métallique ouverte avec gaines souples, isolant et bâti-support visibles.",
    caption: "Cloison ouverte montrant l’ossature métallique, plusieurs gaines souples, l’isolant et un bâti-support encastré.",
    category: "cloison",
  },
  {
    src: "/images/realisations/cloison-plaques-platre-reseaux-plomberie.jpg",
    alt: "Cloison en plaques de plâtre avec raccordements de plomberie apparents dans une pièce en cours de travaux.",
    caption: "Cloison en plaques de plâtre partiellement traitée, avec sorties de plomberie visibles et joints encore non finalisés.",
    category: "cloison",
  },
  {
    src: "/images/realisations/ossature-metallique-plafond-en-cours-02.jpg",
    alt: "Ossature métallique visible sous une charpente, avec des échelles et un échafaudage dans une pièce en travaux.",
    caption: "Mise en place d'une ossature métallique pour plafond dans une pièce en cours d'aménagement.",
    category: "plafond",
  },
  {
    src: "/images/realisations/isolation-plafond-chantier-renovation.jpg",
    alt: "Isolation et ossature de plafond en cours dans une pièce en rénovation.",
    caption: "Préparation de l'isolation et du plafond avant fermeture par les plaques de plâtre.",
    category: "isolation",
  },
  {
    src: "/images/realisations/plafond-panneaux-entre-poutres.jpg",
    alt: "Plafond avec panneaux posés entre des poutres en bois dans une pièce en chantier.",
    caption: "Panneaux installés entre les poutres en bois, avec des profilés métalliques et de l'outillage au sol.",
    category: "plafond",
  },
  {
    src: "/images/realisations/plafond-entre-poutres-en-cours.jpg",
    alt: "Pièce en chantier avec des panneaux posés entre des poutres en bois et des profilés métalliques au sol.",
    caption: "Le plafond entre poutres est en cours d'aménagement, avec des matériaux et des outils de chantier visibles au sol.",
    category: "plafond",
  },
  {
    src: "/images/realisations/ossature-metallique-doublage-mur-en-cours.jpg",
    alt: "Rails métalliques fixés sur un mur en parpaings pour préparer un doublage intérieur.",
    caption: "Mise en place de rails métalliques sur un mur en parpaings, avec une ouverture et une échelle visibles dans la pièce.",
    category: "doublage",
  },
  {
    src: "/images/realisations/pose-plaques-platre-sous-poutres.jpg",
    alt: "Plaques de plâtre posées au plafond entre des poutres en bois, avec des rails métalliques fixés sur un mur en blocs.",
    caption: "Plafond en plaques de plâtre en cours de pose entre les poutres apparentes, dans une pièce en chantier.",
    category: "plafond",
  },
  {
    src: "/images/realisations/pose-isolation-murs-plafond.jpg",
    alt: "Panneaux isolants visibles sur les murs sous une charpente apparente et un plafond incliné.",
    caption: "Des panneaux isolants sont posés sur les murs, tandis que les poutres en bois restent apparentes sous le plafond incliné.",
    category: "isolation",
  },
  {
    src: "/images/realisations/pose-isolation-murs-ossature.jpg",
    alt: "Murs intérieurs avec panneaux isolants visibles entre montants métalliques, avant pose des plaques.",
    caption: "Isolation des murs en cours dans une pièce, avec les montants métalliques et les panneaux isolants apparents.",
    category: "isolation",
  },
  {
    src: "/images/realisations/pose-isolation-murs-plafond-02.jpg",
    alt: "Pièces en cours d'isolation avec des panneaux visibles sur les murs et entre les poutres du plafond.",
    caption: "Isolation visible sur les murs et au plafond dans une pièce en cours de chantier, avec poutres apparentes et sol non fini.",
    category: "isolation",
  },
  {
    src: "/images/realisations/ossature-metallique-cloison-en-cours.jpg",
    alt: "Ossature métallique d'une cloison en cours de montage dans une pièce avec plafond en plaques.",
    caption: "Une ossature métallique est installée pour former une cloison, tandis que le plafond présente des plaques et des joints visibles.",
    category: "cloison",
  },
  {
    src: "/images/realisations/ossature-metallique-cloison-en-cours-02.jpg",
    alt: "Ossature métallique d'une future cloison intérieure en cours de montage devant un mur maçonné.",
    caption: "Mise en place d’une ossature métallique pour une future cloison dans un espace intérieur.",
    category: "cloison",
  },
  {
    src: "/images/realisations/ossature-metallique-cloison-en-cours-03.jpg",
    alt: "Ossature métallique visible sur une cloison en cours d'aménagement dans une pièce en chantier.",
    caption: "L'ossature métallique de la future cloison est visible devant un mur en blocs, avec des outils entreposés dans la pièce.",
    category: "cloison",
  },
  {
    src: "/images/realisations/ossature-metallique-plafond-isolation.jpg",
    alt: "Plafond en cours de chantier avec ossature métallique, isolation apparente et câbles électriques.",
    caption: "Ossature métallique visible sous le plafond, avec isolation apparente et réseaux de câbles en attente.",
    category: "plafond",
  },
  {
    src: "/images/realisations/plafond-a-niveaux-avec-cable.jpg",
    alt: "Plafond à plusieurs niveaux avec une gaine ou un câble apparent au centre de la pièce.",
    caption: "Plafond à plusieurs niveaux avec une réservation périphérique et une gaine apparente en attente.",
    category: "plafond",
  },
  {
    src: "/images/realisations/ossature-metallique-plafond-en-cours-03.jpg",
    alt: "Ossature métallique suspendue sous une charpente avec gaines, câbles et équipements techniques visibles.",
    caption: "Mise en place d'une ossature métallique de plafond avec réseaux techniques apparents dans un espace en construction.",
    category: "plafond",
  },
  {
    src: "/images/realisations/plafond-decoratif-mur-tv-eclaire.jpg",
    alt: "Pièce intérieure avec plafond décoratif éclairé, télévision murale et éléments muraux arrondis.",
    caption: "Plafond à formes décoratives avec éclairage encastré et mur TV doté d’éléments arrondis éclairés.",
    category: "decoratif",
  },
  {
    src: "/images/realisations/plafond-plaques-platre-joints-en-cours.jpg",
    alt: "Plafond en plaques de plâtre avec joints enduits et gaines électriques apparentes dans une pièce en rénovation.",
    caption: "Les joints du plafond en plaques de plâtre sont enduits, tandis que des gaines électriques restent apparentes.",
    category: "plafond",
  },
  {
    src: "/images/realisations/isolation-mur-ossature-metallique.jpg",
    alt: "Panneaux isolants installés entre des montants métalliques avec des câbles apparents et deux fenêtres.",
    caption: "Isolation d’un mur en cours de pose entre une ossature métallique, avec câblage apparent et plaques non encore installées.",
    category: "isolation",
  },
  {
    src: "/images/realisations/plafond-plaques-platre-cables-electriques.jpg",
    alt: "Pièce en chantier avec plafond en plaques de plâtre, câbles électriques apparents et isolation visible sur les murs.",
    caption: "Plafond en plaques de plâtre installé dans une pièce en cours d’aménagement, avec câbles électriques apparents et isolation visible.",
    category: "plafond",
  },
  {
    src: "/images/realisations/finition-joints-plaques-platre-plafond.jpg",
    alt: "Plafond et plaques de plâtre murales en cours de finition avec joints enduits.",
    caption: "Les joints et raccords d’un plafond avec retombée ainsi que de plaques de plâtre murales sont en cours d’enduisage.",
    category: "joints-finitions",
  },
  {
    src: "/images/realisations/ossature-metallique-mur-isole.jpg",
    alt: "Mur en cours de réalisation avec montants métalliques, panneaux isolants visibles et câbles électriques apparents.",
    caption: "Ossature métallique installée devant des panneaux isolants, avec câbles électriques en attente et plafond en plaques de plâtre.",
    category: "isolation",
  },
  {
    src: "/images/realisations/joints-plaques-platre-mur-plafond.jpg",
    alt: "Mur et plafond en plaques de plâtre avec joints et points de fixation enduits.",
    caption: "Les joints et points de fixation des plaques de plâtre sont en cours de finition sur le mur et le plafond.",
    category: "joints-finitions",
  },
  {
    src: "/images/realisations/piece-interieure-murs-briques-reseaux-apparents.jpg",
    alt: "Mur intérieur en briques avant doublage, avec réseaux techniques apparents sous une charpente en bois.",
    caption: "Préparation de la pièce et des réseaux avant la réalisation du doublage intérieur.",
    category: "doublage",
  },
  {
    src: "/images/realisations/doublage-plaques-platre-en-cours.jpg",
    alt: "Mur recouvert de plaques de plâtre avec ossature de plafond et gaines électriques visibles dans une pièce en chantier.",
    caption: "Les plaques de plâtre sont posées sur un mur, tandis que l’ossature du plafond et plusieurs gaines restent apparentes.",
    category: "doublage",
  },
  {
    src: "/images/realisations/plaques-platre-murs-plafond-en-cours.jpg",
    alt: "Pièce en cours d’aménagement avec des plaques de plâtre posées aux murs et au plafond, et des câbles apparents.",
    caption: "Plaques de plâtre visibles sur les murs et le plafond d’une pièce en chantier, avec des câbles électriques en attente.",
    category: "cloison",
  },
  {
    src: "/images/realisations/ossature-metallique-doublage-mur.jpg",
    alt: "Ossature métallique installée devant un mur en briques avec plusieurs fenêtres dans une pièce en chantier.",
    caption: "Mise en place d'une ossature métallique devant un mur en briques, autour des fenêtres, avant la pose du parement.",
    category: "doublage",
  },
  {
    src: "/images/realisations/pose-isolation-murs-pare-vapeur.jpg",
    alt: "Panneaux isolants avec pare-vapeur visibles sur les murs d'une pièce en cours de chantier.",
    caption: "Pose de l'isolation murale autour des fenêtres avant réalisation du parement intérieur.",
    category: "isolation",
  },
  {
    src: "/images/realisations/pose-isolation-murs-ossature-metallique.jpg",
    alt: "Isolation visible entre des montants métalliques autour de plusieurs fenêtres, avec des câbles apparents.",
    caption: "Isolation maintenue entre les montants métalliques avant fermeture du doublage.",
    category: "isolation",
  },
  {
    src: "/images/realisations/isolation-murs-pare-vapeur-en-cours.jpg",
    alt: "Pièce en chantier avec isolation et pare-vapeur visibles sur les murs, fenêtres posées et ossature métallique apparente.",
    caption: "Mise en place de l'isolation et du pare-vapeur avant réalisation du doublage intérieur.",
    category: "isolation",
  },
  {
    src: "/images/realisations/pose-isolation-ossature-metallique-mur.jpg",
    alt: "Mur en cours d'isolation avec panneaux isolants et ossature métallique visibles.",
    caption: "Préparation d'un doublage isolé avec mise en place des panneaux et des montants métalliques.",
    category: "isolation",
  },
  {
    src: "/images/realisations/pose-isolation-ossature-doublage.jpg",
    alt: "Panneaux isolants installés entre des montants métalliques autour de deux fenêtres.",
    caption: "Mise en place de l'isolation et de l'ossature métallique avant la pose du parement intérieur.",
    category: "isolation",
  },
  {
    src: "/images/realisations/pose-isolation-pare-vapeur-ossature-metallique.jpg",
    alt: "Isolation avec pare-vapeur visible entre une ossature métallique et un mur en blocs.",
    caption: "Isolation et pare-vapeur intégrés à l'ossature avant fermeture du mur.",
    category: "isolation",
  },
  {
    src: "/images/realisations/plaques-platre-murs-plafond-en-cours-02.jpg",
    alt: "Pièce en cours d’aménagement avec murs et plafond en plaques de plâtre, câbles apparents et mur en briques visible.",
    caption: "Murs et plafond revêtus de plaques de plâtre au cours des travaux de doublage intérieur.",
    category: "doublage",
  },
  {
    src: "/images/realisations/pose-plaques-platre-murs-plafond.jpg",
    alt: "Pièce en cours d’aménagement avec plaques de plâtre posées sur les murs et au plafond, câbles et conduits encore visibles.",
    caption: "Les murs et le plafond sont partiellement recouverts de plaques de plâtre dans une pièce en cours de chantier.",
    category: "doublage",
  },
  {
    src: "/images/realisations/pose-isolation-mur-en-cours.jpg",
    alt: "Un ouvrier met en place une isolation sur un mur entre des montants métalliques, avec deux fenêtres visibles.",
    caption: "Pose d’une isolation murale en cours dans une pièce équipée de deux fenêtres.",
    category: "isolation",
  },
  {
    src: "/images/realisations/isolation-murs-en-cours.jpg",
    alt: "Murs recouverts d'un isolant visible dans une pièce en travaux, avec deux fenêtres et un plafond terminé.",
    caption: "Isolation visible sur les murs d'une pièce en cours d'aménagement, avec deux fenêtres et un sol non fini.",
    category: "isolation",
  },
  {
    src: "/images/realisations/pose-isolation-murs-fenetres.jpg",
    alt: "Murs recouverts de panneaux isolants protégés par un film imprimé autour de deux fenêtres.",
    caption: "Isolation en cours de pose sur les murs d'une pièce avec deux fenêtres, avant finition.",
    category: "isolation",
  },
] as const
